networks:

  app-network:

volumes:

    app-volume:

services:

  public:
    build: ./public
    image: olaab_chatapp_frontend
    container_name: public
    networks:
      - app-network
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build: ./server
    image: olaab_chatapp_backend
    container_name: server
    networks:
      - app-network
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mongo:4.4
    container_name: mongo
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - app-volume:/data/db
